name : Create PR for Prod branch after Push event on Main Branch.

on:
  push:
    branches:
      main
    paths:
      - 'config.ini'
      - 'configuration.py'
      - 'db_config.ini'
      - 'db_ingest_script.py'
      - 'dbutils.py'
      - 'queries.py'
      - 'requirements.txt'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out code from main
      uses: actions/checkout@v4
      with:
        token: ${{secrets.GITHUB_TOKEN}}


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Creating Logs folder
      run: |
        echo "$PWD"
        echo "$HOME"
        mkdir Logs

    - name: Configuring S3 access
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
        # Your commands that require AWS credentials
        # For example, configuring AWS CLI:
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure set default.region ap-south-1
        aws s3 ls
      
    - name: Run Python Script
      id: run_script
      run: |
        python db_ingest_script.py 20
      continue-on-error: false
    
    - name: Check for changes and Create PR
      if : success() && github.ref == 'refs/heads/main'
      run : |
        #configure git
        git config user.name "sameer-21B"
        git config user.email "sameerbhosale1999@gmail.com"

        if git diff prod main --exit-code --quiet -- db_config.ini dbutils.py config.ini queries.py configuration.py db_ingest_script.py requirements.txt; then 
          echo "No changes detected by the python script. Skipping PR creation."
        else
          BRANCH_NAME="auto-pr-$(date +%Y%m%d%H%M%S)"
          echo Branch_name is $BRANCH_NAME
          echo Switching to PROD.
          git checkout prod

          echo creating $BRANCH_NAME branch
          git checkout -b $BRANCH_NAME 

          git add .
          git commit -m "Automating changes for PR script"

          git push origin $BRANCH_NAME

          echo "Creating a Pull Request..."
          gh pr create --base prod --head $BRAHCN_NAME --title "Automated PR from python script" --body "This PR was automatically generated by a GitHub Actions workflow after a successful run of your_script.py."
        fi
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

       
