name : Create PR for Prod branch after Push event on Main Branch.

on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checking out code from main
      uses: actions/checkout@v4
      with:
        token: ${{secrets.GITHUB_TOKEN}}


    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Creating Logs folder
      run: |
        echo "$PWD"
        echo "$HOME"
        mkdir Logs

    - name: Configuring S3 access
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      run: |
        # Your commands that require AWS credentials
        # For example, configuring AWS CLI:
        aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID"
        aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY"
        aws configure set default.region ap-south-1
        aws s3 ls
      
    - name: Run Python Script
      id: run_script
      run: |
        python db_ingest_script.py
      continue-on-error: false
    
    - name: Check for changes and Create PR
      if : success() && github.ref == 'refs/heads/main'
      run : |
        #configure git
        git config user.name "Github Action Bot"
        git config user.email "actions@github.com"

        if git diff --exit-code --quiet; then 
          echo "No changes detected by the python script. Skipping PR creation."
        else
          BRANCH_NAME = "auto-pr-$(date + %Y%m%d%H%M%S)"
          git checkout -b BRANCH_NAME 

          git add .
          git commit -m "Automating changes for PR script"

          git push origin $BRAHCN_NAME

          echo "Creating a Pull Request..."
          gh pr create --base prod --head $BRAHCN_NAME --title "Automated PR from python script" --body "This PR was automatically generated by a GitHub Actions workflow after a successful run of your_script.py."
        fi
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

       
